[Icon Theme]
Name=coloured
Comment=Coloured Theme

Directories=actions/16x16,actions/24x24,actions/32x32,mimetypes/16x16,preferences/32x32

[actions/16x16]
Size=16
Context=Actions
Type=Fixed

[actions/24x24]
Size=24
Context=Actions
Type=Fixed

[actions/32x32]
Size=32
Context=Actions
Type=Fixed

[mimetypes/16x16]
Size=16
Context=MimeTypes
Type=Fixed

[preferences/32x32]
Size=32
Context=Preferences
Type=Fixed
